### ISSUE TITLE
Import libp2p-crypto dependants directly

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/js-libp2p-noise#114]
This library depends and imports from `libp2p-crypto` which hosts multiple crypto libs and utils. Since noise only requires a subset of those, should this library skip the `libp2p-crypto` middleman and import strictly what's necessary directly @achingbrain ?

Related: https://github.com/libp2p/js-libp2p-crypto/pull/215

**Comment by achingbrain** [comment]
This sounds appealing but it would make it much easier to end up with multiple versions of dependencies and/or competing implementations of the same algorithms which would increase bundle sizes when libp2p-* modules are packaged up for the browser, plus you still have it as a transitive dependency through peer-id.

Looking into the code here, `libp2p-crypto` is only used to verify the payload of incoming messages - you could use the `pubKey` property on the incoming `peerId` to do the same thing.  Then you could make `libp2p-crypto` a dev dep - eg: https://github.com/ChainSafe/js-libp2p-noise/pull/115

**Comment by wemeetagain** [comment]
resolved with #116
