### ISSUE TITLE
Fails to run in browser because of undefined process global in constants.ts

### ISSUE THREAD

**Issue by tchardin** [ChainSafe/js-libp2p-noise#117]
When building with esbuild with browser as target, the file constants.ts still gets bundled with and crashes in the browser. I would open a PR removing it but have no idea what it does so I've been working with a fork where I removed it. Not sure why this hasn't been caught before maybe my bundle settings are wrong.

**Comment by mpetrunic** [comment]
Can you paste error stacktrace and your build config here?

**Comment by tchardin** [comment]
Sorry for the delay @mpetrunic!
The stack trace is:
```sh
Uncaught ReferenceError: process is not defined
    at node_modules/libp2p-noise/dist/src/constants.js (app.js:37189)
    at __require2 (app.js:20)
    at node_modules/libp2p-noise/dist/src/logger.js (app.js:37203)
    at __require2 (app.js:20)
    at node_modules/libp2p-noise/dist/src/handshakes/abstract-handshake.js (app.js:37285)
    at __require2 (app.js:20)
    at node_modules/libp2p-noise/dist/src/handshakes/xx.js (app.js:37435)
    at __require2 (app.js:20)
    at node_modules/libp2p-noise
```
The esbuild config is:
```js
const esbuild = require('esbuild');

(async () => {
  await esbuild.build({
    entryPoints: {
      app: 'src/index.ts',
    },
    bundle: true,
    outdir: '.',
    metafile: true,
  });
})();
```
If you'd like to reproduce you can just pull this branch: https://github.com/whyrusleeping/libp2p-bencher/pull/1. You can rebundle with the latest version of libp2p-noise and run `go run .` it will open the browser and you will see the error.

Thanks!

**Comment by mpetrunic** [comment]
Hey @tchardin, I've open PR to clarify esbuild config: https://github.com/ChainSafe/js-libp2p-noise/pull/122

That said, you should also use our latest package: "@chainsafe/libp2p-noise": "^5.0.0." instead of deprecated "libp2p-noise" package.

**Comment by tchardin** [comment]
Thanks a lot @mpetrunic! Confirming this fixes my issue.
