### ISSUE TITLE
Add auto-generated CHANGELOG step to release pipeline

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-noise#121]
The v5.0.0 release failed in CI because the CHANGELOG was not updated.

See https://github.com/ChainSafe/js-libp2p-noise/runs/4433002833?check_suite_focus=true

To avoid having this issue again, we should add a step to our github workflow to autogenerate CHANGELOG entries from previous git commits.

As an example, see the gossipsub release workflow: https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/.github/workflows/release.yml

**Comment by mpetrunic** [comment]
I wonder if there is some api param or github action that would trigger this: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
