### ISSUE TITLE
Add integration testing with other libp2p implementations

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-noise#128]
We should have tests that ensure that any release is compatible with other libp2p implementations.

See #127

**Comment by mpetrunic** [comment]
https://github.com/libp2p/interop

Its already here

**Comment by mpetrunic** [comment]
Seems like 

> https://github.com/libp2p/interop
> 

Seems like tests can be now run as part of CI here.
@achingbrain Would it make sense for the interop repo to export tests individually as well? Running pubsub tests in this repo makes little sense or?

**Comment by achingbrain** [comment]
Sounds good, yes
