### ISSUE TITLE
Allow callers to optionally specify the prologue

### ISSUE THREAD

**Issue by John-LittleBearLabs** [ChainSafe/js-libp2p-noise#181]
While it's certainly nice to be allowed to let it default, it could also be useful to be _able_ to specify it.

This came up as I was working on an implementation for a new transport. I'd like to use this library, but the draft spec calls for a specific prologue. We could probably work around it downstream, but it seems cleaner and nicer to me to land a fix here that others can use.

**Comment by mpetrunic** [comment]
resolved via https://github.com/ChainSafe/js-libp2p-noise/pull/182

**Comment by mpetrunic** [comment]
:robot: Release is at https://github.com/ChainSafe/js-libp2p-noise/releases/tag/v8.0.0 :sunflower:
