### ISSUE TITLE
Migrate to as-chacha20poly1305

### ISSUE THREAD

**Issue by p-shahi** [ChainSafe/js-libp2p-noise#255]
### Done Criteria

Use [as-chacha20poly1305](https://www.npmjs.com/package/@chainsafe/as-chacha20poly1305) instead of the stablelib variant: [stablelib.ts#L4](https://github.com/ChainSafe/js-libp2p-noise/blob/master/src/crypto/stablelib.ts#L4)

### Motivation

Reduce performance penalities caused by the stablelib version. See [slack](https://filecoinproject.slack.com/archives/C03K82MU486/p1670276284237439?thread_ts=1669817835.906269&cid=C03K82MU486).

**Comment by bajtos** [comment]
If our goal is to improve the performance in Node.js, maybe it's better to use the native implementation of ChaCha20-Poly1305 provided by the Node.js crypto API?

_Cross-posting code snippets from https://www.derpturkey.com/chacha20poly1305-aead-with-node-js/_

Encryption:

```js
// example 96-bit nonce
let nonce = Buffer.alloc(12, 0xff);

// example 256-bit key
let key = Buffer.alloc(32, 0x01);

// some associated data 
let assocData = Buffer.alloc(16, 0xaa);

// some data to encrypt
let data = Buffer.alloc(64, 0xbb);

// construct the cipher
let cipher = crypto.createCipheriv('chacha20-poly1305', key, nonce, { authTagLength: 16 });

// add associated data to cipher
cipher.setAAD(assocData);

// encrypt the data which will return an encrypted Buffer
// that is of equal length to the overall input to the
// stream cipher
cipher.update(data);
// 25805b670d5834ecb8a018ea87b6ff864117762481880fc723690d0e2d0cfd08a43c144291eb2df148b0d6981b66ca101344ea27c7a0860c2e5f1a7eed1e70eb

// finalize cipher which allows us to calculate the MAC
cipher.final();

// obtain the 128-bit poly1305 MAC that includes our associated data
cipher.getAuthTag()
// 9ef622cec7a5719261031e9ca91049d4
```

Decryption:

```js
// same 96-bit nonce
let nonce = Buffer.alloc(12, 0xff);

// same 256-bit key
let key = Buffer.alloc(32, 0x01);

// same associated data
let assocData = Buffer.alloc(16, 0xaa);

// auth tag from encryption output
let authTag = Buffer.from("9ef622cec7a5719261031e9ca91049d4", "hex");

// cipher data from encryption output
let cipherData = Buffer.from("25805b670d5834ecb8a018ea87b6ff864117762481880fc723690d0e2d0cfd08a43c144291eb2df148b0d6981b66ca101344ea27c7a0860c2e5f1a7eed1e70eb", "hex");

// create decipher
let decipher = crypto.createDecipheriv("chacha20-poly1305", key, nonce, { authTagLength: 16 });

// set associated data
decipher.setAAD(assocData);

// decrypt data, which should be the initial data
decipher.update(cipherData);
// bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

// set the auth tag received during encryption
decipher.setAuthTag(authTag);

// validate the MAC is ok => this will throw an
// exception if the cipher, assoc data, or auth tag are
// inaccurate
decipher.final();
```

**Comment by bajtos** [comment]
According to https://github.com/nodejs/Release, Node.js 14 is the oldest LTS release that is still supported.

Node.js 14 does support ChaCha20-Poly1305, you can verify it like this:

```
❯ node
Welcome to Node.js v14.21.2.
Type ".help" for more information.
> crypto.getCiphers().filter(p => p.startsWith('chacha'))
[ 'chacha20', 'chacha20-poly1305' ]
```

**Comment by bajtos** [comment]
Maybe we could completely replace stablelib with Node.js built-in APIs.

(1)
How to generate a `x25519` keypair - quoting from https://stackoverflow.com/q/61898215/69868:

```js
const crypto = require('crypto');
const { publicKey, privateKey } = crypto.generateKeyPairSync('x25519', {
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem'
  },
  privateKeyEncoding: {
    type: 'pkcs8',
    format: 'pem',
  }
});
```

The code above works in Node.js 14 💪🏻 

(2)
HKDF was added to Node.js 16, see https://www.nearform.com/blog/getting-to-know-hkdf/

```js
const { hkdf, hkdfSync } = require('crypto');

hkdf('sha512', 'key', 'salt', 'info', 64, (err, derivedKey) => {
  if (err) throw err;
  console.log(Buffer.from(derivedKey).toString('hex'));  // '24156e2...5391653'
});

const derivedKey = hkdfSync('sha512', 'key', 'salt', 'info', 64);
console.log(Buffer.from(derivedKey).toString('hex'));  // '24156e2...5391653'
```

(3) Both SHA-256 and SHA-512 hashes can be computed using the built-in `crypto.Hash` API - see the docs: https://nodejs.org/api/crypto.html#class-hash

```js
const {createHash} = require('node:crypto');

const hash = createHash('sha256');
hash.update('some data to hash');
console.log(hash.digest('hex'));
```

I think that's all we need to create a Node.js-native version of [src/crypto/stablelib.ts](https://github.com/ChainSafe/js-libp2p-noise/blob/master/src/crypto/stablelib.ts).

Thoughts?

I am happy to contribute these changes if you can give me a few pointers on where to start. In particular:
- How to setup two versions of `src/crypto/stabelib.ts` - one for the browser and another for Node.js
- How to verify that the new version works both in Node.js and the browser. Do I need to write any new tests, or is it enough to run the current test suite?
- How to measure the performance before and after my change?

**Comment by mpetrunic** [comment]
> * How to setup two versions of `src/crypto/stabelib.ts` - one for the browser and another for Node.js

Just implement ICryptoInterface with nodejs API like we did for stablelib: https://github.com/ChainSafe/js-libp2p-noise/blob/master/src/crypto/stablelib.ts

> * How to verify that the new version works both in Node.js and the browser. Do I need to write any new tests, or is it enough to run the current test suite?

You should probably run existing suites against both nodejs crypto and stablelib. They should verify implementation is correct.

> * How to measure the performance before and after my change?

You should add nodejs benchmarks and run: https://github.com/ChainSafe/js-libp2p-noise/blob/master/package.json#L53

Would love if you would be able to contribute this, although we should probably keep stablelib for browser^^

**Comment by bajtos** [comment]
@mpetrunic thank you!

> we should probably keep stablelib for browser

Yes, let's keep stablelib for browser.

In the future, we may want to leverage WebCrypto instead of stablelib, but I am not sure what's the support status for the individual features we need.

Ideally, we would have only one implementation using WebCrypto both in the browser and in Node.js, but I think browsers & Node.js are not there yet. Maybe in 6-18 months?

**Comment by marcus-pousette** [comment]
I am working on a Bitswap like protocol and ran into serious bottlenecks from the chacha impl. I did some work last two nights to benchmarking and see how I could improve this lib:

Code: https://github.com/dao-xyz/js-libp2p-noise

So for browsers environments I am now using [libsodium.js](https://www.npmjs.com/package/libsodium-wrappers). I am seeing 20%-50% performance improvement. 

For Node, I am using the Node crypto lib and I am seeing 500-700% performance improvement.

I am targeting ES2022 as I use top level await to load the libsodium WASM module

Other things one can improve with the code (which I will try out later) 

- Remove all dependencies on DataView and use Uint8Arrays directly and write the encoders and decoders by hand. (DataView creation is very slow in my experience)

- There is a lot of subarray calls in ´encoder.ts´. I think it is possible to do a zero copy solution where this is not necessary.

**Comment by marcus-pousette** [comment]
> Maybe we could completely replace stablelib with Node.js built-in APIs.
> 
> (1) How to generate a `x25519` keypair - quoting from https://stackoverflow.com/q/61898215/69868:
> 
> ```js
> const crypto = require('crypto');
> const { publicKey, privateKey } = crypto.generateKeyPairSync('x25519', {
>   publicKeyEncoding: {
>     type: 'spki',
>     format: 'pem'
>   },
>   privateKeyEncoding: {
>     type: 'pkcs8',
>     format: 'pem',
>   }
> });
> ```
> 
> The code above works in Node.js 14 💪🏻
> 
> Related: https://github.com/libp2p/js-libp2p-crypto/blob/master/src/keys/ed25519.ts
> 
> (2) HKDF was added to Node.js 16, see https://www.nearform.com/blog/getting-to-know-hkdf/
> 
> ```js
> const { hkdf, hkdfSync } = require('crypto');
> 
> hkdf('sha512', 'key', 'salt', 'info', 64, (err, derivedKey) => {
>   if (err) throw err;
>   console.log(Buffer.from(derivedKey).toString('hex'));  // '24156e2...5391653'
> });
> 
> const derivedKey = hkdfSync('sha512', 'key', 'salt', 'info', 64);
> console.log(Buffer.from(derivedKey).toString('hex'));  // '24156e2...5391653'
> ```
> 
> (3) Both SHA-256 and SHA-512 hashes can be computed using the built-in `crypto.Hash` API - see the docs: https://nodejs.org/api/crypto.html#class-hash
> 
> ```js
> const {createHash} = require('node:crypto');
> 
> const hash = createHash('sha256');
> hash.update('some data to hash');
> console.log(hash.digest('hex'));
> ```
> 
> I think that's all we need to create a Node.js-native version of [src/crypto/stablelib.ts](https://github.com/ChainSafe/js-libp2p-noise/blob/master/src/crypto/stablelib.ts).
> 
> Thoughts?
> 
> I am happy to contribute these changes if you can give me a few pointers on where to start. In particular:
> 
> * How to setup two versions of `src/crypto/stabelib.ts` - one for the browser and another for Node.js
> * How to verify that the new version works both in Node.js and the browser. Do I need to write any new tests, or is it enough to run the current test suite?
> * How to measure the performance before and after my change?

I tried doing all keygen in Node.js crypto. Interesting enough, it is very hard to get better performance than stablelib + libsodium.js combo. 

Annoying thing is that you need to use Node.js 19.3 (?) because hkdf does not support empty 'info' prior to that. However, running a system one Node 19.3 actually yields much worse performance on CHACHA encpytion/decryption for some reason. Even a custom hdfk solution with Node.js crypto hash will be slow because you can not reuse a hash instance so you end up doing expensive copies. 

In addition to that, Node.js keygen does not support seeded derivation, and it also generates keys in a format that needs to be exported, to 'der' format, then needs to be sliced into 32 Uint8Arrays. If you don't export, you will end up with two types of private keys in the codebase. Anyway, doing the exporting somewhat optimally is still not faster, because you also need to import/recreate the keys later when doing shared key derivation.

**Comment by bajtos** [comment]
Thank you @marcus-pousette for looking into this issue, you are awesome!

> I am working on a Bitswap like protocol and ran into serious bottlenecks from the chacha impl. I did some work last two nights to benchmarking and see how I could improve this lib:
> (...)
> For Node it uses Node crypto lib and I am seeing 500-700% speed improvement.

Excellent!

> I tried doing all keygen in Node.js crypto. Interesting enough, it is very hard to get better performance than stablelib + libsodium.js combo.

In that case, to keep thing simple, I propose to use the implementation we have in browser for Node.js too.

As far as I am concerned, even if we end up improving only the chacha encryption/decryption  performance, and leave everything else as it is know, then it will be a great improvement.

I am afraid I don't have bandwidth to look into this in January, but I hope to be able to spend few hours a week starting from February.

**Comment by paulmillr** [comment]
Quick heads up: https://github.com/paulmillr/noble-ciphers are out, and it is 1.64x faster than stablelib:

```
chacha20_poly1305 (encrypt, 1MB)
├─stablelib x 117 ops/sec @ 8ms/op
├─noble x 193 ops/sec @ 5ms/op
```

It's important to keep pure js versions around, as you know.
