### ISSUE TITLE
bug: not importable via script tag from CDN

### ISSUE THREAD

**Issue by SgtPooki** [ChainSafe/js-libp2p-noise#296]
even the URL from your README.md is throwing an error: 

![image](https://user-images.githubusercontent.com/1173416/226988278-700e5125-9177-4a60-9920-236609b65061.png)

see https://github.com/ipfs-examples/helia-examples/pull/13 where the only module I couldn't import via unpkg, skypack, or jsdelivr is this package.

when importing from typical CDNs, the files are not appropriately configured for ESM imports on the web, and you will get errors like:

* `  import {noise} from 'https://cdn.jsdelivr.net/npm/@chainsafe/libp2p-noise@11.0.1/dist/src/index.js'
` -> `Uncaught TypeError: Failed to resolve module specifier "it-pb-stream". Relative references must start with either "/", "./", or "../".`
* `<script src="https://cdn.jsdelivr.net/npm/@chainsafe/libp2p-noise@11.0.1/dist/src/index.js" type="module" defer></script>` -> `Uncaught TypeError: Failed to resolve module specifier "it-pb-stream". Relative references must start with either "/", "./", or "../".`

In order to import from CDN, the best provider I found was esm.sh via `import { noise } from 'https://esm.sh/v111/@chainsafe/libp2p-noise@11.0.1/es2022/libp2p-noise.js'

**Comment by SgtPooki** [comment]
@mpetrunic  because it doesn't exist. maybe that's the bug?

![image](https://user-images.githubusercontent.com/1173416/227302056-fae8c60a-5264-400e-9815-a7b34037195a.png)

**Comment by mpetrunic** [comment]
@SgtPooki You are right, indeed. Opened PR with fix #297 Thnx for reporting^^
