### ISSUE TITLE
How do I run the interop tests? 

### ISSUE THREAD

**Issue by marcus-pousette** [ChainSafe/js-libp2p-noise#358]
I cloned the repo 

```
npm install 
```

```
npm run test:interop 
``` 

I get following error

```sh

  connect using noise/ed25519
    1) "before all" hook for "js peer to js peer"


  0 passing (35ms)
  1 failing

  1) connect using noise/ed25519
       "before all" hook for "js peer to js peer":
     Error: Not started
      at Server.getMultiaddr (file:///Users/admin/git/chainsafe/js-libp2p-noise/node_modules/@libp2p/daemon-server/src/index.ts:220:11)
      at createJsPeer (file:///Users/admin/git/chainsafe/js-libp2p-noise/test/interop.ts:89:33)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Context.<anonymous> (file:///Users/admin/git/chainsafe/js-libp2p-noise/node_modules/@libp2p/interop/src/connect.ts:32:17)


```

Seems like the lip2p daemon is never starting

**Comment by marcus-pousette** [comment]
In

[/test/interop.ts](https://github.com/ChainSafe/js-libp2p-noise/blob/master/test/interop.ts)

Replacing all addresses that are 

0.0.0.0 

with

127.0.0.1 

in 

seem to fix the issue for me.

Is something wrong we my local setup for this to be the case?

**Comment by mpetrunic** [comment]
It's working fine on CI https://github.com/ChainSafe/js-libp2p-noise/actions/runs/5753035505/job/15595425850 and for me locally so I guess it's something with your local setup 🤷🏻‍♂️

**Comment by marcus-pousette** [comment]
> It's working fine on CI https://github.com/ChainSafe/js-libp2p-noise/actions/runs/5753035505/job/15595425850 and for me locally so I guess it's something with your local setup 🤷🏻‍♂️

Yes. I saw that, i guess I am not able to listen to 0.0.0.0 on my local setup for some reason. I will close this.
