### ISSUE TITLE
Error while importing the package

### ISSUE THREAD

**Issue by l3lackcurtains** [ChainSafe/js-libp2p-noise#434]
When importing noise from the package
```
const { noise } = require("@chainsafe/libp2p-noise");
```
It says
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined
```

**Comment by achingbrain** [comment]
This is a ESM only package, that means you need to use `import` and not `require`.

Further reading: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
